Azure Deploy

diff --git a/.github/workflows/nginxaas-apply.yaml b/.github/workflows/nginxaas-apply.yaml
--- a/.github/workflows/nginxaas-apply.yaml
+++ b/.github/workflows/nginxaas-apply.yaml
@@ -26,6 +26,15 @@ jobs:
         uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 1.3.0
+      
+      - name: Verify SSH Key
+        run: |
+         if [ -z "${{ secrets.TF_VAR_ssh_public_key }}" ]; then
+           echo "::error::SSH public key is empty!"
+           exit 1
+         else
+          echo "SSH key is set (first 10 chars: ${${{ secrets.TF_VAR_ssh_public_key }}:0:10})"
+         fi
 
       - name: Terraform Init
         run: terraform init
@@ -47,14 +56,7 @@ jobs:
           TF_VAR_nginx_plus_cert: ${{ secrets.TF_VAR_nginx_plus_cert }}
           TF_VAR_nginx_plus_key: ${{ secrets.TF_VAR_nginx_plus_key }}
 
-      - name: Verify SSH Key
-        run: |
-         if [ -z "${{ secrets.TF_VAR_ssh_public_key }}" ]; then
-           echo "::error::SSH public key is empty!"
-           exit 1
-         else
-          echo "SSH key is set (first 10 chars: ${${{ secrets.TF_VAR_ssh_public_key }}:0:10})"
-         fi
+   
       - name: Terraform Apply
         run: terraform apply -input=false -auto-approve
         env:
